maven jar plugin with default manifest
evolvedbinary/PLMultiAnalyzer pull request #10
Opened 2022-01-18 11:27 UTC by marmoure

using the default manifest 
```xml
<plugin>
    <artifactId>maven-jar-plugin</artifactId>
    <version>2.6</version>
    <configuration>
        <useDefaultManifestFile>true</useDefaultManifestFile>
    </configuration>
</plugin>
```

2022-01-26 14:42 UTC, adamretter requested changes
Some small improvements please

2022-01-26 14:42 UTC, adamretter commented on pom.xml
> +                            <addClasspath>true</addClasspath>
We don't want to add the classpath for this project. You only add the classpath to projects that have a `main` function (i.e. are executable), this project is a library.

2022-01-26 14:42 UTC, adamretter commented on pom.xml
> +    <packaging>jar</packaging>
Jar is the default - so you can exclude this line.

2022-01-26 14:48 UTC, marmoure commented on pom.xml
> +                <version>2.6</version>
the tutorial i followed was from few years ago i didnt notice that

2022-02-03 11:34 UTC, adamretter commented on pom.xml
> +                            <Source-Repository>${project.scm.connection}</Source-Repository>
@marmoure The `project` properties you are referencing here need to be set. Take a look here:

1. You need an `<scm>` section. Example here - https://github.com/digital-preservation/utf8-validator/blob/master/pom.xml#L33
2. You need a `<description>`. Example here - https://github.com/digital-preservation/utf8-validator/blob/master/pom.xml#L16
3. You need a `<url>`. Example here -https://github.com/digital-preservation/utf8-validator/blob/master/pom.xml#L17

2022-02-08 15:02 UTC, adamretter commented on pom.xml
> +		<git.base>github.com/${git.account}/${project.artifactId}</git.base>
As per the eXist-db community call - I think we both agree that using properties for the SCM section makes it hard to understand as a human - can you just repeat the full and correct urls in the scm section and remove these `git.` properties please?

2022-02-08 17:07 UTC, merged